name: 'npm caching'
description: 'npm caching'
inputs:
  paths-of-folder:  # id of input
    description: 'the path to cache'
    required: true
runs:
  using: "composite"
  steps:
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ${{ inputs.paths-of-folder }}
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          
      - name: Install dependencies
        run: npm install
