name: Solar system continuous integration

on:
  workflow_dispatch:
  push:
    branches:
     - main
     - 'feature/*'

env:
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'

jobs:
  unit-testing:
    name: Unit-testing
    strategy:
      matrix:
        nodejs_version: [18,20,22]
        operating_system: [ubuntu-latest,macos-latest]
        exclude:
         - nodejs_version: 18
           operating_system: macos-latest
      
    runs-on: ${ matrix.operating_system }
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js - ${{ matrix.nodejs_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nodejs_version }}
          
      - name: Install dependencies
        run: npm install

      - name: Unit testing
        run: npm test

      - uses: actions/upload-artifact@v4
        with:
          name: Mocha-test-result
          path: test-results.xml
