name: Create a CI pipeline

on:
    workflow_dispatch: 


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout to repo
          uses: actions/checkout@v2

        - name: Setup node
          uses: actions/setup-node@v3
          with:
            node-version: 18
            cache: 'npm'

        - name: Install dependency
          run: npm ci

        - name: testing npm
          run: npm test